# ======================
# DATABASE CONFIG
# ======================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================
# SERVER CONFIG
# ======================
server.port=8081

# ======================
# JPA WARNING SUPPRESSION (optional)
# ======================
spring.jpa.open-in-view=false